neo4j:
  name: "test-cluster"
  resources:
    cpu: "0.5"
    memory: "2Gi"
  password: "secret"
  acceptLicenseAgreement: "yes"

nodeSelector:
  topology.kubernetes.io/zone: "eu-central-1c"
volumes:
  data:
    mode: "volume"
    volume:
      awsElasticBlockStore:
        # The ID of the awsElasticBlockStore volume you have created for this cluster member.
        volumeID: "vol-0089268de67e14b53"
        fsType: ext4
