neo4j:
  name: "test-cluster"
  resources:
    cpu: "0.5"
    memory: "2Gi"
  password: "secret"
  acceptLicenseAgreement: "yes"

volumes:
  data:
    mode: "volume"
    volume:
      awsElasticBlockStore:
        # The ID of the awsElasticBlockStore volume you have created for this cluster member.
        volumeID: "vol-07fc3c1187c31cacd"
        fsType: ext4
